services:
  mongodb:
    image: mongo:7.0
    container_name: recing-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: recing

volumes:
  mongodb-data:
