apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recing-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recing-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recing-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recing-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "recing"
        - name: POSTGRES_USER
          value: "recing"
        - name: POSTGRES_PASSWORD
          value: "recing"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 512Mi
            cpu: 500m
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "recing"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: recing-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: recing-postgres
spec:
  selector:
    app: recing-postgres
  ports:
  - port: 5432
    targetPort: 5432
