#!/usr/bin/env node
/**
 * Generates recipe-extraction-schema.json from the Zod schema.
 *
 * Run: pnpm run gen-json-schema
 *
 * The JSON Schema is derived from `baseSchema` in src/recipe-extraction.ts — the same
 * single source of truth used for runtime validation — so it cannot drift from it.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { baseSchema } from "../src/recipe-extraction.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ─── Generate ────────────────────────────────────────────────────────────────

const jsonSchema = baseSchema.toJSONSchema({ io: "input" });
// Strict: reject unknown fields the LLM might add
(jsonSchema as Record<string, unknown>).additionalProperties = false;

const outJsonPath = join(__dirname, "..", "src", "recipe-extraction-schema.json");
const outJsPath = join(__dirname, "..", "src", "recipe-extraction-schema.js");
const content = JSON.stringify(jsonSchema, null, 2) + "\n";

writeFileSync(outJsonPath, content, "utf-8");

// Write a .js wrapper so it can be imported without JSON import syntax
const jsContent = [
  "// @ts-check",
  "/**",
  " * Recipe extraction JSON Schema for LLM response_format.",
  " *",
  " * Generated from the Zod schema via `pnpm run gen-json-schema`.",
  " * Do not edit this file manually — run the generator after changing recipe-extraction.ts.",
  " */",

  "/** @type {import('../node_modules/zod/v4/core/to-json-schema.js').ZodStandardJSONSchemaPayload<any>} */",
  "export default " + JSON.stringify(jsonSchema, null, 2) + ";",
  "",
].join("\n");

writeFileSync(outJsPath, jsContent, "utf-8");
console.log(`Written: ${outJsonPath}, ${outJsPath}`);
