#!/usr/bin/env node
/**
 * Generates recipe-extraction-schema.json from the Zod schema.
 *
 * Run: pnpm run gen-json-schema
 *
 * After modifying packages/schema/src/recipe-extraction.ts, regenerate with:
 *   pnpm run gen-json-schema
 * Then commit the updated JSON file.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { z } from "zod";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ─── Replicate the Zod schema (must match recipe-extraction.ts) ──────────────

const nullString = (schema: z.ZodType<string>) =>
  schema.nullish().transform((v) => v ?? null);

const nullableQuantity = z
  .union([z.string(), z.number()])
  .nullish()
  .transform((v) => (v === undefined || v === null ? null : String(v)));

const ingredientSchema = z.object({
  quantity: nullableQuantity,
  unit: nullString(z.string()),
  name: z.string().min(1),
  note: nullString(z.string()),
  originalText: z.string().min(1),
});

const instructionSchema = z.object({
  stepNumber: z.number().int().min(1),
  text: z.string().min(1),
  timer: nullString(z.string()),
});

const baseSchema = z.object({
  schemaVersion: nullString(z.literal("recipe_extraction.v1")),
  status: z.enum(["extracted", "unusable"]),
  sourceUrl: nullString(z.string().url()),
  recipeName: nullString(z.string()),
  description: nullString(z.string()),
  prepTime: nullString(z.string()),
  cookTime: nullString(z.string()),
  totalTime: nullString(z.string()),
  servings: nullString(z.string()),
  cuisine: nullString(z.string()),
  category: nullString(z.string()),
  keywords: nullString(z.string()),
  ingredients: ingredientSchema.array().optional().default([]),
  instructions: instructionSchema.array().optional().default([]),
  notes: z.array(z.string().min(1)).optional().default([]),
  unusableReason: nullString(z.string()),
});

// ─── Generate ────────────────────────────────────────────────────────────────

const jsonSchema = baseSchema.toJSONSchema({ io: "input" });
// Strict: reject unknown fields the LLM might add
(jsonSchema as Record<string, unknown>).additionalProperties = false;

const outJsonPath = join(__dirname, "..", "src", "recipe-extraction-schema.json");
const outJsPath = join(__dirname, "..", "src", "recipe-extraction-schema.js");
const content = JSON.stringify(jsonSchema, null, 2) + "\n";

writeFileSync(outJsonPath, content, "utf-8");

// Write a .js wrapper so it can be imported without JSON import syntax
const jsContent = [
  "// @ts-check",
  "/**",
  " * Recipe extraction JSON Schema for LLM response_format.",
  " *",
  " * Generated from Zod schema via `pnpm run gen-json-schema`.",
  " * Do not edit this file manually — run the generator after changing recipe-extraction.ts.",
  " */",
  "",
  "/** @type {import('../node_modules/zod/v4/core/to-json-schema.js').ZodStandardJSONSchemaPayload<any>} */",
  "export default " + JSON.stringify(jsonSchema, null, 2) + ";",
  "",
].join("\n");

writeFileSync(outJsPath, jsContent, "utf-8");
console.log(`Written: ${outJsonPath}, ${outJsPath}`);
